FROM directus/directus:latest
# Expose the necessary port
EXPOSE 8055

# Set the environment variables
ENV KEY=replace-with-random-value \
    SECRET=replace-with-random-value \
    ADMIN_EMAIL=admin@example.com \
    ADMIN_PASSWORD=d1r3ctu5 \
    DB_CLIENT=sqlite3 \
    DB_FILENAME=/directus/data.db \
    WEBSOCKETS_ENABLED=true